# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp4', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set([('site_name', 'title', 'video_url')]),
        ),
    ]
