# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 03:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp4', '0002_auto_20161007_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='img_url',
            field=ckeditor.fields.RichTextField(verbose_name='快照网址'),
        ),
    ]
