# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 03:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp4', '0003_auto_20161007_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelists',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
