# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='')),
                ('fromlink', models.CharField(blank=True, max_length=200, null=True, verbose_name='来源')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='名称')),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='代码')),
            ],
            options={
                'verbose_name_plural': '链接类型',
            },
        ),
        migrations.CreateModel(
            name='Sitelists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='抓取栏目名称')),
                ('link', models.URLField(unique=True, verbose_name='链接地址')),
                ('utf8', models.BooleanField(default=True, verbose_name='UTF-8编码')),
                ('autofetch', models.BooleanField(default=True, verbose_name='自动抓取')),
                ('disabled', models.BooleanField(default=False, verbose_name='关闭')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_category', to='joke.Category', verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '抓取栏目',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='标识名称')),
                ('isSearched', models.BooleanField(default=True)),
                ('isDisabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'TAG',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sitelists', to='joke.Sitelists', verbose_name='网站'),
        ),
        migrations.AddField(
            model_name='articles',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_articles', to='joke.Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='articles',
            unique_together=set([('title', 'site', 'fromlink')]),
        ),
    ]
