# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0003_articles_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
